import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.Timer; // Important for safe removal while iterating
import java.awt.Font;

/**
 * The main game panel where all game objects are drawn and updated.
 * Manages the game loop, object spawning, and collision detection.
 */
public class GamePanel extends JPanel implements ActionListener {

    // Public static final constants for screen dimensions, accessible by other classes
    public static final int SCREEN_WIDTH = 800;
    public static final int SCREEN_HEIGHT = 600;

    private Player player;
    private ArrayList<GameObject> gameObjects; // The key ArrayList for polymorphism!
    private Timer gameLoopTimer; // Controls the game's frame rate
    private int score;
    private boolean isGameOver;

    private long lastEnemySpawnTime = 0;
    private long lastPowerUpSpawnTime = 0;
    private final long ENEMY_SPAWN_DELAY = 1000; // milliseconds between enemy spawns
    private final long POWERUP_SPAWN_DELAY = 7000;

    /**
     * Constructor for GamePanel.
     * Sets up the panel, initializes game objects, and starts the game loop.
     */
    public GamePanel() {
        setPreferredSize(new Dimension(SCREEN_WIDTH, SCREEN_HEIGHT));
        setBackground(Color.BLACK); // Black background for space theme
        setFocusable(true); // JPanel must be focusable to receive keyboard input

        // Initialize game objects
        // Player is positioned at the bottom center
        player = new Player(SCREEN_WIDTH / 2 - 25, SCREEN_HEIGHT - 70, 50, 50, 5, 3);
        gameObjects = new ArrayList<>();
        gameObjects.add(player); // Add the player to the list of all game objects
        score = 0;
        isGameOver = false;
        
        // Add key listener for player input
        addKeyListener(new GameKeyListener());

        // Setup game loop timer (e.g., 60 frames per second)
        // The Timer calls actionPerformed() repeatedly
        gameLoopTimer = new Timer(1000 / 60, this); // 1000ms / 60 = ~16ms per frame
        gameLoopTimer.start(); // Start the game loop
    }

    /**
     * Called automatically by Swing to paint the component.
     * Iterates through all active game objects and calls their draw() method.
     * @param g The Graphics object used for drawing.
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Clear the panel
        // Iterate through all game objects and draw them polymorphically
        for (GameObject obj : gameObjects) {
            if (obj.isActive()) { // Only draw active objects
                obj.draw(g);
            }
        }
        g.setColor(Color.WHITE);
        g.drawString("score: " + score, 20, 20);
        
        if(isGameOver){
            g.setFont( new Font("Arial", Font.BOLD, 100)   );
            g.drawString("Game Over Sucker", 200, 200);
            gameLoopTimer.stop();
        }
        if(score >= 20){
            g.setFont( new Font("Arial", Font.BOLD, 100)   );
            g.drawString("You Win", 200, 200);
            gameLoopTimer.stop();
        }
    }
    

    /**
     * This method is called repeatedly by the gameLoopTimer.
     * It contains the core game logic for updating object states, spawning, and collisions.
     * @param e The ActionEvent generated by the Timer.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        
        
        
        // 1. Update all game objects
        // Use an Iterator for safe removal of objects while iterating
        Iterator<GameObject> iterator = gameObjects.iterator();
        while (iterator.hasNext()) {
            GameObject obj = iterator.next();
            obj.update(); // Call the specific update method for each object type
            if (!obj.isActive()) {
                iterator.remove(); // Remove inactive objects (e.g., off-screen enemies/projectiles)
            }
        }
        
        

        // 2. Spawn new enemies
        long currentTime = System.currentTimeMillis();
        if (currentTime - lastEnemySpawnTime > ENEMY_SPAWN_DELAY) {
            // Spawn enemy at a random x-position at the top of the screen
            int enemyX = (int) (Math.random() * (SCREEN_WIDTH - 40)); // 40 is enemy width
            
            String[] enemyTypeList = {"shield", "classic"};
            int enemyTypeListIndex = (int)(Math.random() * enemyTypeList.length);
            
            if(enemyTypeList[enemyTypeListIndex] == "shield"){
                gameObjects.add(new EnemyShield(enemyX, 0, 40, 40, 2));
            }
            if(enemyTypeList[enemyTypeListIndex] == "classic"){
                gameObjects.add(new EnemyClassic(enemyX, 0, 40, 40, 2, 1));
            }
            
            //gameObjects.add(new Enemy(enemyX, 0, 40, 40, 2, 1)); // Add new enemy to the list
            lastEnemySpawnTime = currentTime;
        }
        // spawn powerpus
        
        
        if(currentTime - lastPowerUpSpawnTime > POWERUP_SPAWN_DELAY){
            int powerUpX = (int)(Math.random() * (SCREEN_WIDTH - 40));
            String[] powerUpTypeList = {"speed", "health"};
            int enemyTypeListIndex = (int)(Math.random() * powerUpTypeList.length);
            
            if(powerUpTypeList[enemyTypeListIndex].equals("speed")){
                gameObjects.add(new SpeedPowerUp(powerUpX, 0, 20, 20, 2));    
            }
            if(powerUpTypeList[enemyTypeListIndex].equals("health")){
                gameObjects.add(new HealthPowerUp(powerUpX, 0, 20, 20, 2));    
            }
            
            lastPowerUpSpawnTime = currentTime;
            
        }

        // 3. Handle Collisions (Simplified - students will expand this)
        // Iterate through projectiles and enemies to check for collisions
        // Create copies of the list to avoid ConcurrentModificationException when removing
        ArrayList<GameObject> currentObjects = new ArrayList<>(gameObjects);
        for (GameObject proj : currentObjects) {
            if (proj instanceof Projectile && proj.isActive()) { // Check if it's an active projectile
                for (GameObject enemy : currentObjects) {
                    if (enemy instanceof Enemy && enemy.isActive()) { // Check if it's an active enemy
                        // Check for intersection of their bounding boxes
                        if (proj.getBounds().intersects(enemy.getBounds())) {
                            // Collision detected!
                            proj.setActive(false); // Deactivate projectile
                            //enemy.setActive(false); // Deactivate enemy
                            ((Enemy)enemy).subtractHealth(1);
                            // Students can add score updates, sound effects, etc., here
                            if(((Enemy)enemy).getHealth() == 0){
                                score+=1;
                            }
                            
                        }
                        
                    }
                }
            }
            
            
        }
        
        // dpes enemy logic
        for(GameObject enemy : currentObjects){
            if(enemy instanceof Enemy && enemy.isActive()){
                if(player.getBounds().intersects(enemy.getBounds())){

                    ((Enemy)enemy).subtractHealth(1);
                    player.subtractHealth(1);
                }
            }
        }
        
        //powerup logic
        for(GameObject powerUp : currentObjects){
            if(powerUp instanceof PowerUp && powerUp.isActive()){
                if(player.getBounds().intersects(powerUp.getBounds())){
                    powerUp.setActive(false);
                    String current = ((PowerUp)powerUp).getWhatPowerUp();
                    switch(current){
                        
                        case "health":
                            player.addHealth(1);
                        case "speed":
                            player.addSpeed(2);
  
                    } 
                }              
            }
        }
        
        // is game over
        for(GameObject enemy : currentObjects){
            if(enemy.getY() > SCREEN_HEIGHT || player.getHealth() == 0){

                    isGameOver = true;
                    
            }
        }
        
        // 4. Repaint the panel to show updated positions and new objects
        repaint();
    }

    /**
     * Inner class to handle keyboard input for the game.
     * Extends KeyAdapter to only override necessary methods.
     */
    private class GameKeyListener extends KeyAdapter {
        /**
         * Called when a key is pressed.
         * Controls player movement and shooting.
         * @param e The KeyEvent generated by the key press.
         */
        @Override
        public void keyPressed(KeyEvent e) {
            player.keyPressed(e.getKeyCode()); // Delegate movement to Player class
            if (e.getKeyCode() == KeyEvent.VK_SPACE) {
                // When space is pressed, create a new Projectile
                // Position the projectile at the center of the player's top edge
                Projectile p = new Projectile(player.getX() + player.getWidth() / 2 - 5,
                                              player.getY(), 10, 20, 10);
                gameObjects.add(p); // Add the new projectile to the game objects list
            }
        }

        /**
         * Called when a key is released.
         * Stops player movement when movement keys are released.
         * @param e The KeyEvent generated by the key release.
         */
        @Override
        public void keyReleased(KeyEvent e) {
            player.keyReleased(e.getKeyCode()); // Delegate stopping movement to Player class
        }
    }
}
